name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # SCP to upload compiled files to EC2
          scp -i private_key.pem -r ./dist/* $USER@$HOST:/home/ubuntu/my-express-app/dist/
          
          # SSH to EC2 and use PM2 to run the compiled app.js
          ssh -i private_key.pem $USER@$HOST "pm2 start /home/ubuntu/my-express-app/dist/app.js --name my-express-app"
